#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

_JRS_DEPLOYING=`head -1 $OPENSHIFT_REPO_DIR/.openshift/action_hooks/deploying-war-info`

cd ${OPENSHIFT_TMP_DIR}/${_JRS_DEPLOYING}/buildomatic

   # echo "------> Running: js-ant create-js-db ..."
   # ./js-ant create-js-db
echo "------> Running: js-ant init-js-db-ce ..."
./js-ant init-js-db-ce
echo "------> Running: js-ant import-minimal-ce ..."
./js-ant import-minimal-ce
echo "-----> Running: js-ant deploy-webapp-ce ..."
./js-ant deploy-webapp-ce
echo " done"
   #update the currently deployed war
echo ${_JRS_DEPLOYING} >> ${OPENSHIFT_DATA_DIR}/deployed-war-info
