#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

#
## Liferay Portal deployment directory, its the core portal and not the plugins
#

_JRS_PORTAL_DEPLOYED=`head -1 ${OPENSHIFT_DATA_DIR}/deployed-war-info`

_JRS_DEPLOY_DIR="${OPENSHIFT_DATA_DIR}jasperreports"

echo "Trigger deployment for : ${_JRS_DEPLOY_DIR}/${_JRS_DEPLOYED}.dodeploy"

touch ${_JRS_DEPLOY_DIR}/${_JRS_DEPLOYED}.dodeploy
